name: hermes_harbor_flutter_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  animate_do: ^4.2.0
  flex_color_scheme: ^8.1.0
  awesome_bottom_bar: ^1.2.4
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  loading_animation_widget: ^1.2.1
  flutter_animate: ^4.5.2
  hexcolor: ^3.0.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  skeletonizer: ^1.4.3
  gpt_markdown: ^1.0.18
  heroine: ^0.4.0+1
  animations: ^2.0.11
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/carousels/
