// Sample product data - replace with your actual data source
import 'package:flutter/material.dart';
import 'package:hermes_harbor_flutter_app/models/product.dart';

final List<Product> demoProducts = [
  Product(
    id: 'p1',
    name: 'Minimalist Chair',
    description: 'A sleek and modern chair that fits perfectly in any space.',
    price: 129.99,
    images: [
      'https://images.pexels.com/photos/4352247/pexels-photo-4352247.jpeg',
    ],
    rating: 4.8,
    isFavorite: false,
    tags: ['chair', 'minimalist', 'furniture'],
    availableColors: [Colors.white, Colors.black],
    brand: 'Eames',
    category: 'Chairs',
    features: ['Leatherette Upholstery', 'Metal Frame', 'Adjustable Height'],
    reviewCount: 42,
    createdAt: DateTime(2025, 1, 15),
  ),
  Product(
    id: 'p2',
    name: 'Nordic Table',
    description: 'Scandinavian-inspired wooden table, both sturdy and stylish.',
    price: 299.99,
    images: [
      'https://images.pexels.com/photos/3736390/pexels-photo-3736390.jpeg',
    ],
    rating: 4.6,
    isFavorite: true,
    tags: ['table', 'nordic', 'wood'],
    availableColors: [Colors.brown, Colors.black],
    brand: 'IKEA',
    category: 'Tables',
    features: ['Solid Wood', 'Metal Legs', 'Adjustable Height'],
    reviewCount: 32,
    createdAt: DateTime(2025, 2, 10),
  ),
  Product(
    id: 'p3',
    name: 'Modern Sofa',
    description: 'A comfy and elegant sofa perfect for lounging in style.',
    price: 899.99,
    images: [
      'https://images.pexels.com/photos/3757055/pexels-photo-3757055.jpeg',
    ],
    rating: 4.9,
    isFavorite: false,
    tags: ['sofa', 'modern', 'living room'],
    availableColors: [Colors.white, Colors.black],
    brand: 'IKEA',
    category: 'Sofas',
    features: ['Leatherette Upholstery', 'Metal Frame', 'Adjustable Height'],
    reviewCount: 52,
    createdAt: DateTime(2025, 3, 5),
  ),
  Product(
    id: 'p4',
    name: 'Industrial Lamp',
    description: 'A rugged lamp that gives off warm, ambient lighting.',
    price: 79.99,
    images: [
      'https://images.pexels.com/photos/3679601/pexels-photo-3679601.jpeg',
    ],
    rating: 4.5,
    isFavorite: true,
    tags: ['lamp', 'industrial', 'lighting'],
    availableColors: [Colors.white, Colors.black],
    brand: 'IKEA',
    category: 'Lamps',
    features: ['Metal Frame', 'Adjustable Height', 'LED Light'],
    reviewCount: 22,
    createdAt: DateTime(2025, 4, 20),
  ),
  Product(
    id: 'p5',
    name: 'Scandinavian Shelf',
    description: 'Wall-mounted shelf with a clean design and practical space.',
    price: 199.99,
    images: [
      'https://images.pexels.com/photos/3736439/pexels-photo-3736439.jpeg',
    ],
    rating: 4.7,
    isFavorite: false,
    tags: ['shelf', 'scandinavian', 'decor'],
    availableColors: [Colors.white, Colors.black],
    brand: 'IKEA',
    category: 'Shelves',
    features: ['Solid Wood', 'Metal Legs', 'Adjustable Height'],
    reviewCount: 12,
    createdAt: DateTime(2025, 5, 15),
  ),
];
