import 'package:flutter/material.dart';

import '../components/home/home_screen_categories.dart';
import '../models/product.dart';

final List<Product> menCategoryProducts = [
  Product(
    id: 'm1',
    name: 'Slim Fit Denim Jacket',
    description: 'Classic blue denim with a modern slim fit cut.',
    price: 89.99,
    images: [
      'https://images.pexels.com/photos/626165/pexels-photo-626165.jpeg',
    ],
    rating: 4.7,
    isFavorite: false,
    tags: ['jacket', 'denim', 'men'],
    availableColors: [Colors.blue, Colors.black],
    brand: 'Levi\'s',
    category: categories[0].name,
    features: ['Slim Fit', 'Button Closure', 'Two Chest Pockets'],
    reviewCount: 37,
    createdAt: DateTime(2025, 1, 5),
  ),
  Product(
    id: 'm2',
    name: 'White Sneakers',
    description: 'Minimalist sneakers that go with literally everything.',
    price: 59.99,
    images: [
      'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg',
    ],
    rating: 4.8,
    isFavorite: true,
    tags: ['sneakers', 'shoes', 'men'],
    availableColors: [Colors.white],
    brand: 'Nike',
    category: categories[0].name,
    features: ['Rubber Sole', 'Lightweight', 'Breathable Material'],
    reviewCount: 54,
    createdAt: DateTime(2025, 2, 12),
  ),
  Product(
    id: 'm3',
    name: 'Casual Hoodie',
    description: 'Stay cozy with this fleece-lined men\'s hoodie.',
    price: 49.99,
    images: [
      'https://images.pexels.com/photos/5704847/pexels-photo-5704847.jpeg',
    ],
    rating: 4.6,
    isFavorite: false,
    tags: ['hoodie', 'casual', 'men'],
    availableColors: [Colors.grey, Colors.black],
    brand: 'H&M',
    category: categories[0].name,
    features: ['Fleece Lined', 'Drawstring Hood', 'Kangaroo Pocket'],
    reviewCount: 29,
    createdAt: DateTime(2025, 3, 18),
  ),
  Product(
    id: 'm4',
    name: 'Aviator Sunglasses',
    description: 'Timeless sunglasses for that Top Gun aesthetic.',
    price: 129.99,
    images: [
      'https://images.pexels.com/photos/1478441/pexels-photo-1478441.jpeg',
    ],
    rating: 4.9,
    isFavorite: true,
    tags: ['sunglasses', 'accessories', 'men'],
    availableColors: [Colors.black],
    brand: 'Ray-Ban',
    category: categories[0].name,
    features: ['UV Protection', 'Metal Frame', 'Polarized Lenses'],
    reviewCount: 66,
    createdAt: DateTime(2025, 4, 8),
  ),
  Product(
    id: 'm5',
    name: 'Leather Belt',
    description: 'Durable leather belt that completes any look.',
    price: 39.99,
    images: [
      'https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg',
    ],
    rating: 4.5,
    isFavorite: false,
    tags: ['belt', 'leather', 'men'],
    availableColors: [Colors.brown, Colors.black],
    brand: 'Gucci',
    category: categories[0].name,
    features: ['Genuine Leather', 'Metal Buckle', 'Adjustable Length'],
    reviewCount: 21,
    createdAt: DateTime(2025, 5, 2),
  ),
];
