import 'package:flutter/material.dart';

import '../components/home/home_screen_categories.dart';
import '../models/product.dart';

final List<Product> womenCategoryProducts = [
  Product(
    id: 'w1',
    name: 'Floral Midi Dress',
    description: 'A light and flowy floral dress perfect for spring days.',
    price: 79.99,
    images: [
      'https://images.pexels.com/photos/7619631/pexels-photo-7619631.jpeg',
    ],
    rating: 4.9,
    isFavorite: true,
    tags: ['dress', 'floral', 'women'],
    availableColors: [Colors.pink, Colors.white],
    brand: 'Zara',
    category: categories[1].name,
    features: ['Breathable Fabric', 'A-Line Cut', 'Hidden Zipper'],
    reviewCount: 58,
    createdAt: DateTime(2025, 3, 10),
  ),
  Product(
    id: 'w2',
    name: 'Elegant Handbag',
    description: 'Stylish handbag that pairs perfectly with any outfit.',
    price: 119.99,
    images: [
      'https://images.pexels.com/photos/167703/pexels-photo-167703.jpeg',
    ],
    rating: 4.7,
    isFavorite: false,
    tags: ['handbag', 'accessory', 'women'],
    availableColors: [Colors.brown, Colors.black],
    brand: 'Michael Kors',
    category: categories[1].name,
    features: ['Leather Finish', 'Adjustable Strap', 'Multiple Compartments'],
    reviewCount: 44,
    createdAt: DateTime(2025, 2, 20),
  ),
  Product(
    id: 'w3',
    name: 'Oversized Sunglasses',
    description: 'Make a bold statement with these oversized shades.',
    price: 89.99,
    images: [
      'https://images.pexels.com/photos/842811/pexels-photo-842811.jpeg',
    ],
    rating: 4.8,
    isFavorite: true,
    tags: ['sunglasses', 'fashion', 'women'],
    availableColors: [Colors.black],
    brand: 'Versace',
    category: categories[1].name,
    features: ['UV Protection', 'Durable Frame', 'Gradient Lenses'],
    reviewCount: 39,
    createdAt: DateTime(2025, 4, 5),
  ),
  Product(
    id: 'w4',
    name: 'High Waist Jeans',
    description: 'Flattering high-waisted jeans for an everyday fit.',
    price: 69.99,
    images: [
      'https://images.pexels.com/photos/2968735/pexels-photo-2968735.jpeg',
    ],
    rating: 4.6,
    isFavorite: false,
    tags: ['jeans', 'denim', 'women'],
    availableColors: [Colors.blue],
    brand: 'H&M',
    category: categories[1].name,
    features: ['Stretch Fit', 'Ankle Length', 'Zipper Fly'],
    reviewCount: 33,
    createdAt: DateTime(2025, 1, 28),
  ),
  Product(
    id: 'w5',
    name: 'Classic Heels',
    description: 'Elevate your style with these elegant stiletto heels.',
    price: 99.99,
    images: [
      'https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg',
    ],
    rating: 4.7,
    isFavorite: true,
    tags: ['heels', 'footwear', 'women'],
    availableColors: [Colors.red, Colors.black],
    brand: 'Aldo',
    category: categories[1].name,
    features: ['Pointed Toe', 'Slip-On', 'Leather Upper'],
    reviewCount: 47,
    createdAt: DateTime(2025, 5, 12),
  ),
];
